# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'COMsetDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(372, 295)
        Dialog.setMinimumSize(QtCore.QSize(372, 295))
        Dialog.setMaximumSize(QtCore.QSize(372, 295))
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 151, 201))
        self.groupBox.setObjectName("groupBox")
        self.COM1_Databits_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.COM1_Databits_comboBox.setGeometry(QtCore.QRect(58, 69, 81, 20))
        self.COM1_Databits_comboBox.setObjectName("COM1_Databits_comboBox")
        self.COM1_Databits_comboBox.addItem("")
        self.COM1_Databits_comboBox.addItem("")
        self.COM1_Databits_comboBox.addItem("")
        self.COM1_Databits_comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(11, 27, 48, 16))
        self.label.setObjectName("label")
        self.COM1_Stopbits_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.COM1_Stopbits_comboBox.setGeometry(QtCore.QRect(59, 111, 81, 20))
        self.COM1_Stopbits_comboBox.setObjectName("COM1_Stopbits_comboBox")
        self.COM1_Stopbits_comboBox.addItem("")
        self.COM1_Stopbits_comboBox.addItem("")
        self.COM1_baudrates_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.COM1_baudrates_comboBox.setGeometry(QtCore.QRect(59, 27, 81, 20))
        self.COM1_baudrates_comboBox.setObjectName("COM1_baudrates_comboBox")
        self.COM1_baudrates_comboBox.addItem("")
        self.COM1_baudrates_comboBox.addItem("")
        self.COM1_baudrates_comboBox.addItem("")
        self.COM1_baudrates_comboBox.addItem("")
        self.COM1_baudrates_comboBox.addItem("")
        self.COM1_baudrates_comboBox.addItem("")
        self.COM1_baudrates_comboBox.addItem("")
        self.COM1_baudrates_comboBox.addItem("")
        self.COM1_baudrates_comboBox.addItem("")
        self.COM1_baudrates_comboBox.addItem("")
        self.COM1_baudrates_comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(11, 153, 48, 16))
        self.label_4.setObjectName("label_4")
        self.COM1_paritys_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.COM1_paritys_comboBox.setGeometry(QtCore.QRect(60, 153, 81, 20))
        self.COM1_paritys_comboBox.setObjectName("COM1_paritys_comboBox")
        self.COM1_paritys_comboBox.addItem("")
        self.COM1_paritys_comboBox.addItem("")
        self.COM1_paritys_comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(11, 111, 48, 16))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(11, 69, 48, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(190, 30, 151, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(11, 27, 48, 16))
        self.label_6.setObjectName("label_6")
        self.COM2_Stopbits_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.COM2_Stopbits_comboBox.setGeometry(QtCore.QRect(59, 111, 81, 20))
        self.COM2_Stopbits_comboBox.setObjectName("COM2_Stopbits_comboBox")
        self.COM2_Stopbits_comboBox.addItem("")
        self.COM2_Stopbits_comboBox.addItem("")
        self.COM2_baudrates_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.COM2_baudrates_comboBox.setGeometry(QtCore.QRect(59, 27, 81, 20))
        self.COM2_baudrates_comboBox.setObjectName("COM2_baudrates_comboBox")
        self.COM2_baudrates_comboBox.addItem("")
        self.COM2_baudrates_comboBox.addItem("")
        self.COM2_baudrates_comboBox.addItem("")
        self.COM2_baudrates_comboBox.addItem("")
        self.COM2_baudrates_comboBox.addItem("")
        self.COM2_baudrates_comboBox.addItem("")
        self.COM2_baudrates_comboBox.addItem("")
        self.COM2_baudrates_comboBox.addItem("")
        self.COM2_baudrates_comboBox.addItem("")
        self.COM2_baudrates_comboBox.addItem("")
        self.COM2_baudrates_comboBox.addItem("")
        self.COM2_Databits_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.COM2_Databits_comboBox.setGeometry(QtCore.QRect(59, 69, 81, 20))
        self.COM2_Databits_comboBox.setObjectName("COM2_Databits_comboBox")
        self.COM2_Databits_comboBox.addItem("")
        self.COM2_Databits_comboBox.addItem("")
        self.COM2_Databits_comboBox.addItem("")
        self.COM2_Databits_comboBox.addItem("")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(11, 153, 48, 16))
        self.label_10.setObjectName("label_10")
        self.COM2_paritys_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.COM2_paritys_comboBox.setGeometry(QtCore.QRect(60, 153, 81, 20))
        self.COM2_paritys_comboBox.setObjectName("COM2_paritys_comboBox")
        self.COM2_paritys_comboBox.addItem("")
        self.COM2_paritys_comboBox.addItem("")
        self.COM2_paritys_comboBox.addItem("")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(11, 69, 48, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(11, 111, 48, 16))
        self.label_8.setObjectName("label_8")
        self.read_pushButton = QtWidgets.QPushButton(Dialog)
        self.read_pushButton.setGeometry(QtCore.QRect(111, 249, 75, 23))
        self.read_pushButton.setObjectName("read_pushButton")
        self.ok_pushButton = QtWidgets.QPushButton(Dialog)
        self.ok_pushButton.setGeometry(QtCore.QRect(192, 249, 75, 23))
        self.ok_pushButton.setObjectName("ok_pushButton")
        self.cancel_pushButton = QtWidgets.QPushButton(Dialog)
        self.cancel_pushButton.setGeometry(QtCore.QRect(273, 249, 75, 23))
        self.cancel_pushButton.setObjectName("cancel_pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "串口1"))
        self.COM1_Databits_comboBox.setItemText(0, _translate("Dialog", "5"))
        self.COM1_Databits_comboBox.setItemText(1, _translate("Dialog", "6"))
        self.COM1_Databits_comboBox.setItemText(2, _translate("Dialog", "7"))
        self.COM1_Databits_comboBox.setItemText(3, _translate("Dialog", "8"))
        self.label.setText(_translate("Dialog", "波特率："))
        self.COM1_Stopbits_comboBox.setItemText(0, _translate("Dialog", "1"))
        self.COM1_Stopbits_comboBox.setItemText(1, _translate("Dialog", "2"))
        self.COM1_baudrates_comboBox.setItemText(0, _translate("Dialog", "600"))
        self.COM1_baudrates_comboBox.setItemText(1, _translate("Dialog", "1200"))
        self.COM1_baudrates_comboBox.setItemText(2, _translate("Dialog", "2400"))
        self.COM1_baudrates_comboBox.setItemText(3, _translate("Dialog", "4800"))
        self.COM1_baudrates_comboBox.setItemText(4, _translate("Dialog", "9600"))
        self.COM1_baudrates_comboBox.setItemText(5, _translate("Dialog", "14400"))
        self.COM1_baudrates_comboBox.setItemText(6, _translate("Dialog", "19200"))
        self.COM1_baudrates_comboBox.setItemText(7, _translate("Dialog", "38400"))
        self.COM1_baudrates_comboBox.setItemText(8, _translate("Dialog", "56000"))
        self.COM1_baudrates_comboBox.setItemText(9, _translate("Dialog", "57600"))
        self.COM1_baudrates_comboBox.setItemText(10, _translate("Dialog", "115200"))
        self.label_4.setText(_translate("Dialog", "校验位："))
        self.COM1_paritys_comboBox.setItemText(0, _translate("Dialog", "N"))
        self.COM1_paritys_comboBox.setItemText(1, _translate("Dialog", "O"))
        self.COM1_paritys_comboBox.setItemText(2, _translate("Dialog", "E"))
        self.label_3.setText(_translate("Dialog", "停止位："))
        self.label_2.setText(_translate("Dialog", "数据位："))
        self.groupBox_2.setTitle(_translate("Dialog", "串口2"))
        self.label_6.setText(_translate("Dialog", "波特率："))
        self.COM2_Stopbits_comboBox.setItemText(0, _translate("Dialog", "1"))
        self.COM2_Stopbits_comboBox.setItemText(1, _translate("Dialog", "2"))
        self.COM2_baudrates_comboBox.setItemText(0, _translate("Dialog", "600"))
        self.COM2_baudrates_comboBox.setItemText(1, _translate("Dialog", "1200"))
        self.COM2_baudrates_comboBox.setItemText(2, _translate("Dialog", "2400"))
        self.COM2_baudrates_comboBox.setItemText(3, _translate("Dialog", "4800"))
        self.COM2_baudrates_comboBox.setItemText(4, _translate("Dialog", "9600"))
        self.COM2_baudrates_comboBox.setItemText(5, _translate("Dialog", "14400"))
        self.COM2_baudrates_comboBox.setItemText(6, _translate("Dialog", "19200"))
        self.COM2_baudrates_comboBox.setItemText(7, _translate("Dialog", "38400"))
        self.COM2_baudrates_comboBox.setItemText(8, _translate("Dialog", "56000"))
        self.COM2_baudrates_comboBox.setItemText(9, _translate("Dialog", "57600"))
        self.COM2_baudrates_comboBox.setItemText(10, _translate("Dialog", "115200"))
        self.COM2_Databits_comboBox.setItemText(0, _translate("Dialog", "5"))
        self.COM2_Databits_comboBox.setItemText(1, _translate("Dialog", "6"))
        self.COM2_Databits_comboBox.setItemText(2, _translate("Dialog", "7"))
        self.COM2_Databits_comboBox.setItemText(3, _translate("Dialog", "8"))
        self.label_10.setText(_translate("Dialog", "校验位："))
        self.COM2_paritys_comboBox.setItemText(0, _translate("Dialog", "N"))
        self.COM2_paritys_comboBox.setItemText(1, _translate("Dialog", "O"))
        self.COM2_paritys_comboBox.setItemText(2, _translate("Dialog", "E"))
        self.label_7.setText(_translate("Dialog", "数据位："))
        self.label_8.setText(_translate("Dialog", "停止位："))
        self.read_pushButton.setText(_translate("Dialog", "读取"))
        self.ok_pushButton.setText(_translate("Dialog", "配置"))
        self.cancel_pushButton.setText(_translate("Dialog", "取消"))

