# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F16COMsetDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(287, 509)
        Dialog.setMinimumSize(QtCore.QSize(287, 509))
        Dialog.setMaximumSize(QtCore.QSize(287, 509))
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 241, 131))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.com1_baudrate_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.com1_baudrate_comboBox.setObjectName("com1_baudrate_comboBox")
        self.com1_baudrate_comboBox.addItem("")
        self.com1_baudrate_comboBox.addItem("")
        self.com1_baudrate_comboBox.addItem("")
        self.com1_baudrate_comboBox.addItem("")
        self.com1_baudrate_comboBox.addItem("")
        self.com1_baudrate_comboBox.addItem("")
        self.com1_baudrate_comboBox.addItem("")
        self.com1_baudrate_comboBox.addItem("")
        self.com1_baudrate_comboBox.addItem("")
        self.com1_baudrate_comboBox.addItem("")
        self.com1_baudrate_comboBox.addItem("")
        self.gridLayout.addWidget(self.com1_baudrate_comboBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.com1_parity_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.com1_parity_comboBox.setObjectName("com1_parity_comboBox")
        self.com1_parity_comboBox.addItem("")
        self.com1_parity_comboBox.addItem("")
        self.com1_parity_comboBox.addItem("")
        self.com1_parity_comboBox.addItem("")
        self.com1_parity_comboBox.addItem("")
        self.com1_parity_comboBox.addItem("")
        self.com1_parity_comboBox.addItem("")
        self.com1_parity_comboBox.addItem("")
        self.com1_parity_comboBox.addItem("")
        self.com1_parity_comboBox.addItem("")
        self.gridLayout.addWidget(self.com1_parity_comboBox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.com1_bind_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.com1_bind_comboBox.setObjectName("com1_bind_comboBox")
        self.com1_bind_comboBox.addItem("")
        self.com1_bind_comboBox.addItem("")
        self.com1_bind_comboBox.addItem("")
        self.com1_bind_comboBox.addItem("")
        self.com1_bind_comboBox.addItem("")
        self.com1_bind_comboBox.addItem("")
        self.com1_bind_comboBox.addItem("")
        self.gridLayout.addWidget(self.com1_bind_comboBox, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 160, 241, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.com2_baudrate_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.com2_baudrate_comboBox.setObjectName("com2_baudrate_comboBox")
        self.com2_baudrate_comboBox.addItem("")
        self.com2_baudrate_comboBox.addItem("")
        self.com2_baudrate_comboBox.addItem("")
        self.com2_baudrate_comboBox.addItem("")
        self.com2_baudrate_comboBox.addItem("")
        self.com2_baudrate_comboBox.addItem("")
        self.com2_baudrate_comboBox.addItem("")
        self.com2_baudrate_comboBox.addItem("")
        self.com2_baudrate_comboBox.addItem("")
        self.com2_baudrate_comboBox.addItem("")
        self.com2_baudrate_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.com2_baudrate_comboBox, 0, 1, 1, 1)
        self.com2_parity_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.com2_parity_comboBox.setObjectName("com2_parity_comboBox")
        self.com2_parity_comboBox.addItem("")
        self.com2_parity_comboBox.addItem("")
        self.com2_parity_comboBox.addItem("")
        self.com2_parity_comboBox.addItem("")
        self.com2_parity_comboBox.addItem("")
        self.com2_parity_comboBox.addItem("")
        self.com2_parity_comboBox.addItem("")
        self.com2_parity_comboBox.addItem("")
        self.com2_parity_comboBox.addItem("")
        self.com2_parity_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.com2_parity_comboBox, 1, 1, 1, 1)
        self.com2_bind_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.com2_bind_comboBox.setObjectName("com2_bind_comboBox")
        self.com2_bind_comboBox.addItem("")
        self.com2_bind_comboBox.addItem("")
        self.com2_bind_comboBox.addItem("")
        self.com2_bind_comboBox.addItem("")
        self.com2_bind_comboBox.addItem("")
        self.com2_bind_comboBox.addItem("")
        self.com2_bind_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.com2_bind_comboBox, 2, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 300, 241, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.rs485_baudrate_comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.rs485_baudrate_comboBox.setObjectName("rs485_baudrate_comboBox")
        self.rs485_baudrate_comboBox.addItem("")
        self.rs485_baudrate_comboBox.addItem("")
        self.rs485_baudrate_comboBox.addItem("")
        self.rs485_baudrate_comboBox.addItem("")
        self.rs485_baudrate_comboBox.addItem("")
        self.rs485_baudrate_comboBox.addItem("")
        self.rs485_baudrate_comboBox.addItem("")
        self.rs485_baudrate_comboBox.addItem("")
        self.rs485_baudrate_comboBox.addItem("")
        self.rs485_baudrate_comboBox.addItem("")
        self.rs485_baudrate_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.rs485_baudrate_comboBox, 0, 1, 1, 1)
        self.rs485_parity_comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.rs485_parity_comboBox.setObjectName("rs485_parity_comboBox")
        self.rs485_parity_comboBox.addItem("")
        self.rs485_parity_comboBox.addItem("")
        self.rs485_parity_comboBox.addItem("")
        self.rs485_parity_comboBox.addItem("")
        self.rs485_parity_comboBox.addItem("")
        self.rs485_parity_comboBox.addItem("")
        self.rs485_parity_comboBox.addItem("")
        self.rs485_parity_comboBox.addItem("")
        self.rs485_parity_comboBox.addItem("")
        self.rs485_parity_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.rs485_parity_comboBox, 1, 1, 1, 1)
        self.rs485_bind_comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.rs485_bind_comboBox.setObjectName("rs485_bind_comboBox")
        self.rs485_bind_comboBox.addItem("")
        self.rs485_bind_comboBox.addItem("")
        self.rs485_bind_comboBox.addItem("")
        self.rs485_bind_comboBox.addItem("")
        self.rs485_bind_comboBox.addItem("")
        self.rs485_bind_comboBox.addItem("")
        self.rs485_bind_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.rs485_bind_comboBox, 2, 1, 1, 1)
        self.ok_pushButton = QtWidgets.QPushButton(Dialog)
        self.ok_pushButton.setGeometry(QtCore.QRect(120, 460, 61, 23))
        self.ok_pushButton.setObjectName("ok_pushButton")
        self.cancel_pushButton = QtWidgets.QPushButton(Dialog)
        self.cancel_pushButton.setGeometry(QtCore.QRect(200, 460, 61, 23))
        self.cancel_pushButton.setObjectName("cancel_pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "串口1"))
        self.label.setText(_translate("Dialog", "          波特率："))
        self.com1_baudrate_comboBox.setItemText(0, _translate("Dialog", "600"))
        self.com1_baudrate_comboBox.setItemText(1, _translate("Dialog", "1200"))
        self.com1_baudrate_comboBox.setItemText(2, _translate("Dialog", "2400"))
        self.com1_baudrate_comboBox.setItemText(3, _translate("Dialog", "4800"))
        self.com1_baudrate_comboBox.setItemText(4, _translate("Dialog", "9600"))
        self.com1_baudrate_comboBox.setItemText(5, _translate("Dialog", "14400"))
        self.com1_baudrate_comboBox.setItemText(6, _translate("Dialog", "19200"))
        self.com1_baudrate_comboBox.setItemText(7, _translate("Dialog", "38400"))
        self.com1_baudrate_comboBox.setItemText(8, _translate("Dialog", "56000"))
        self.com1_baudrate_comboBox.setItemText(9, _translate("Dialog", "57600"))
        self.com1_baudrate_comboBox.setItemText(10, _translate("Dialog", "115200"))
        self.label_2.setText(_translate("Dialog", "            校验："))
        self.com1_parity_comboBox.setItemText(0, _translate("Dialog", "8N1"))
        self.com1_parity_comboBox.setItemText(1, _translate("Dialog", "8E1"))
        self.com1_parity_comboBox.setItemText(2, _translate("Dialog", "8O1"))
        self.com1_parity_comboBox.setItemText(3, _translate("Dialog", "7O1"))
        self.com1_parity_comboBox.setItemText(4, _translate("Dialog", "7E1"))
        self.com1_parity_comboBox.setItemText(5, _translate("Dialog", "8N2"))
        self.com1_parity_comboBox.setItemText(6, _translate("Dialog", "8E2"))
        self.com1_parity_comboBox.setItemText(7, _translate("Dialog", "8O2"))
        self.com1_parity_comboBox.setItemText(8, _translate("Dialog", "7O2"))
        self.com1_parity_comboBox.setItemText(9, _translate("Dialog", "7E2"))
        self.label_3.setText(_translate("Dialog", "        通信绑定："))
        self.com1_bind_comboBox.setItemText(0, _translate("Dialog", "关闭"))
        self.com1_bind_comboBox.setItemText(1, _translate("Dialog", "数据中心1"))
        self.com1_bind_comboBox.setItemText(2, _translate("Dialog", "数据中心2"))
        self.com1_bind_comboBox.setItemText(3, _translate("Dialog", "数据中心3"))
        self.com1_bind_comboBox.setItemText(4, _translate("Dialog", "数据中心4"))
        self.com1_bind_comboBox.setItemText(5, _translate("Dialog", "数据中心5"))
        self.com1_bind_comboBox.setItemText(6, _translate("Dialog", "所有中心"))
        self.groupBox_2.setTitle(_translate("Dialog", "串口2"))
        self.label_4.setText(_translate("Dialog", "          波特率："))
        self.label_5.setText(_translate("Dialog", "            校验："))
        self.label_6.setText(_translate("Dialog", "        通信绑定："))
        self.com2_baudrate_comboBox.setItemText(0, _translate("Dialog", "600"))
        self.com2_baudrate_comboBox.setItemText(1, _translate("Dialog", "1200"))
        self.com2_baudrate_comboBox.setItemText(2, _translate("Dialog", "2400"))
        self.com2_baudrate_comboBox.setItemText(3, _translate("Dialog", "4800"))
        self.com2_baudrate_comboBox.setItemText(4, _translate("Dialog", "9600"))
        self.com2_baudrate_comboBox.setItemText(5, _translate("Dialog", "14400"))
        self.com2_baudrate_comboBox.setItemText(6, _translate("Dialog", "19200"))
        self.com2_baudrate_comboBox.setItemText(7, _translate("Dialog", "38400"))
        self.com2_baudrate_comboBox.setItemText(8, _translate("Dialog", "56000"))
        self.com2_baudrate_comboBox.setItemText(9, _translate("Dialog", "57600"))
        self.com2_baudrate_comboBox.setItemText(10, _translate("Dialog", "115200"))
        self.com2_parity_comboBox.setItemText(0, _translate("Dialog", "8N1"))
        self.com2_parity_comboBox.setItemText(1, _translate("Dialog", "8E1"))
        self.com2_parity_comboBox.setItemText(2, _translate("Dialog", "8O1"))
        self.com2_parity_comboBox.setItemText(3, _translate("Dialog", "7O1"))
        self.com2_parity_comboBox.setItemText(4, _translate("Dialog", "7E1"))
        self.com2_parity_comboBox.setItemText(5, _translate("Dialog", "8N2"))
        self.com2_parity_comboBox.setItemText(6, _translate("Dialog", "8E2"))
        self.com2_parity_comboBox.setItemText(7, _translate("Dialog", "8O2"))
        self.com2_parity_comboBox.setItemText(8, _translate("Dialog", "7O2"))
        self.com2_parity_comboBox.setItemText(9, _translate("Dialog", "7E2"))
        self.com2_bind_comboBox.setItemText(0, _translate("Dialog", "关闭"))
        self.com2_bind_comboBox.setItemText(1, _translate("Dialog", "数据中心1"))
        self.com2_bind_comboBox.setItemText(2, _translate("Dialog", "数据中心2"))
        self.com2_bind_comboBox.setItemText(3, _translate("Dialog", "数据中心3"))
        self.com2_bind_comboBox.setItemText(4, _translate("Dialog", "数据中心4"))
        self.com2_bind_comboBox.setItemText(5, _translate("Dialog", "数据中心5"))
        self.com2_bind_comboBox.setItemText(6, _translate("Dialog", "所有中心"))
        self.groupBox_3.setTitle(_translate("Dialog", "RS485"))
        self.label_7.setText(_translate("Dialog", "          波特率："))
        self.label_8.setText(_translate("Dialog", "            校验："))
        self.label_9.setText(_translate("Dialog", "        通信绑定："))
        self.rs485_baudrate_comboBox.setItemText(0, _translate("Dialog", "600"))
        self.rs485_baudrate_comboBox.setItemText(1, _translate("Dialog", "1200"))
        self.rs485_baudrate_comboBox.setItemText(2, _translate("Dialog", "2400"))
        self.rs485_baudrate_comboBox.setItemText(3, _translate("Dialog", "4800"))
        self.rs485_baudrate_comboBox.setItemText(4, _translate("Dialog", "9600"))
        self.rs485_baudrate_comboBox.setItemText(5, _translate("Dialog", "14400"))
        self.rs485_baudrate_comboBox.setItemText(6, _translate("Dialog", "19200"))
        self.rs485_baudrate_comboBox.setItemText(7, _translate("Dialog", "38400"))
        self.rs485_baudrate_comboBox.setItemText(8, _translate("Dialog", "56000"))
        self.rs485_baudrate_comboBox.setItemText(9, _translate("Dialog", "57600"))
        self.rs485_baudrate_comboBox.setItemText(10, _translate("Dialog", "115200"))
        self.rs485_parity_comboBox.setItemText(0, _translate("Dialog", "8N1"))
        self.rs485_parity_comboBox.setItemText(1, _translate("Dialog", "8E1"))
        self.rs485_parity_comboBox.setItemText(2, _translate("Dialog", "8O1"))
        self.rs485_parity_comboBox.setItemText(3, _translate("Dialog", "7O1"))
        self.rs485_parity_comboBox.setItemText(4, _translate("Dialog", "7E1"))
        self.rs485_parity_comboBox.setItemText(5, _translate("Dialog", "8N2"))
        self.rs485_parity_comboBox.setItemText(6, _translate("Dialog", "8E2"))
        self.rs485_parity_comboBox.setItemText(7, _translate("Dialog", "8O2"))
        self.rs485_parity_comboBox.setItemText(8, _translate("Dialog", "7O2"))
        self.rs485_parity_comboBox.setItemText(9, _translate("Dialog", "7E2"))
        self.rs485_bind_comboBox.setItemText(0, _translate("Dialog", "关闭"))
        self.rs485_bind_comboBox.setItemText(1, _translate("Dialog", "数据中心1"))
        self.rs485_bind_comboBox.setItemText(2, _translate("Dialog", "数据中心2"))
        self.rs485_bind_comboBox.setItemText(3, _translate("Dialog", "数据中心3"))
        self.rs485_bind_comboBox.setItemText(4, _translate("Dialog", "数据中心4"))
        self.rs485_bind_comboBox.setItemText(5, _translate("Dialog", "数据中心5"))
        self.rs485_bind_comboBox.setItemText(6, _translate("Dialog", "所有中心"))
        self.ok_pushButton.setText(_translate("Dialog", "配置"))
        self.cancel_pushButton.setText(_translate("Dialog", "取消"))

