# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F16IPandPORTsetDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(391, 439)
        Dialog.setMinimumSize(QtCore.QSize(391, 439))
        Dialog.setMaximumSize(QtCore.QSize(391, 439))
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 351, 208))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 22, 72, 21))
        self.label.setObjectName("label")
        self.serverNum_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.serverNum_comboBox.setGeometry(QtCore.QRect(88, 22, 131, 20))
        self.serverNum_comboBox.setObjectName("serverNum_comboBox")
        self.serverNum_comboBox.addItem("")
        self.serverNum_comboBox.addItem("")
        self.serverNum_comboBox.addItem("")
        self.serverNum_comboBox.addItem("")
        self.serverNum_comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 48, 71, 21))
        self.label_2.setObjectName("label_2")
        self.server_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.server_lineEdit.setGeometry(QtCore.QRect(88, 48, 133, 20))
        self.server_lineEdit.setObjectName("server_lineEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(227, 48, 36, 21))
        self.label_3.setObjectName("label_3")
        self.port_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.port_lineEdit.setGeometry(QtCore.QRect(269, 48, 71, 20))
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 74, 71, 21))
        self.label_4.setObjectName("label_4")
        self.server1_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.server1_lineEdit.setGeometry(QtCore.QRect(88, 74, 133, 20))
        self.server1_lineEdit.setObjectName("server1_lineEdit")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(227, 74, 36, 21))
        self.label_5.setObjectName("label_5")
        self.port1_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.port1_lineEdit.setGeometry(QtCore.QRect(269, 74, 71, 20))
        self.port1_lineEdit.setObjectName("port1_lineEdit")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.label_6.setObjectName("label_6")
        self.server2_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.server2_lineEdit.setGeometry(QtCore.QRect(88, 100, 133, 20))
        self.server2_lineEdit.setObjectName("server2_lineEdit")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(227, 100, 36, 21))
        self.label_7.setObjectName("label_7")
        self.port2_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.port2_lineEdit.setGeometry(QtCore.QRect(269, 100, 71, 20))
        self.port2_lineEdit.setObjectName("port2_lineEdit")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 126, 71, 21))
        self.label_8.setObjectName("label_8")
        self.server3_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.server3_lineEdit.setGeometry(QtCore.QRect(88, 126, 133, 20))
        self.server3_lineEdit.setObjectName("server3_lineEdit")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(227, 126, 36, 21))
        self.label_9.setObjectName("label_9")
        self.port3_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.port3_lineEdit.setGeometry(QtCore.QRect(269, 126, 71, 20))
        self.port3_lineEdit.setObjectName("port3_lineEdit")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 152, 71, 21))
        self.label_10.setObjectName("label_10")
        self.server4_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.server4_lineEdit.setGeometry(QtCore.QRect(88, 152, 133, 20))
        self.server4_lineEdit.setObjectName("server4_lineEdit")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(227, 152, 36, 21))
        self.label_11.setObjectName("label_11")
        self.port4_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.port4_lineEdit.setGeometry(QtCore.QRect(269, 152, 71, 20))
        self.port4_lineEdit.setObjectName("port4_lineEdit")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 178, 71, 21))
        self.label_12.setObjectName("label_12")
        self.server5_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.server5_lineEdit.setGeometry(QtCore.QRect(88, 178, 133, 20))
        self.server5_lineEdit.setObjectName("server5_lineEdit")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(227, 178, 36, 21))
        self.label_13.setObjectName("label_13")
        self.port5_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.port5_lineEdit.setGeometry(QtCore.QRect(269, 178, 71, 20))
        self.port5_lineEdit.setObjectName("port5_lineEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 230, 351, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(60, 20, 91, 20))
        self.label_14.setObjectName("label_14")
        self.reconnect_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.reconnect_lineEdit.setGeometry(QtCore.QRect(160, 20, 113, 20))
        self.reconnect_lineEdit.setObjectName("reconnect_lineEdit")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(90, 50, 71, 21))
        self.label_15.setObjectName("label_15")
        self.reconnectTimes_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.reconnectTimes_lineEdit.setGeometry(QtCore.QRect(160, 50, 113, 20))
        self.reconnectTimes_lineEdit.setObjectName("reconnectTimes_lineEdit")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(70, 80, 81, 21))
        self.label_16.setObjectName("label_16")
        self.reserver_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.reserver_comboBox.setGeometry(QtCore.QRect(160, 80, 111, 22))
        self.reserver_comboBox.setObjectName("reserver_comboBox")
        self.reserver_comboBox.addItem("")
        self.reserver_comboBox.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 380, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 380, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.serverNum_comboBox, self.server_lineEdit)
        Dialog.setTabOrder(self.server_lineEdit, self.port_lineEdit)
        Dialog.setTabOrder(self.port_lineEdit, self.server1_lineEdit)
        Dialog.setTabOrder(self.server1_lineEdit, self.port1_lineEdit)
        Dialog.setTabOrder(self.port1_lineEdit, self.server2_lineEdit)
        Dialog.setTabOrder(self.server2_lineEdit, self.port2_lineEdit)
        Dialog.setTabOrder(self.port2_lineEdit, self.server3_lineEdit)
        Dialog.setTabOrder(self.server3_lineEdit, self.port3_lineEdit)
        Dialog.setTabOrder(self.port3_lineEdit, self.server4_lineEdit)
        Dialog.setTabOrder(self.server4_lineEdit, self.port4_lineEdit)
        Dialog.setTabOrder(self.port4_lineEdit, self.server5_lineEdit)
        Dialog.setTabOrder(self.server5_lineEdit, self.port5_lineEdit)
        Dialog.setTabOrder(self.port5_lineEdit, self.reconnect_lineEdit)
        Dialog.setTabOrder(self.reconnect_lineEdit, self.reconnectTimes_lineEdit)
        Dialog.setTabOrder(self.reconnectTimes_lineEdit, self.reserver_comboBox)
        Dialog.setTabOrder(self.reserver_comboBox, self.pushButton_2)
        Dialog.setTabOrder(self.pushButton_2, self.pushButton_3)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "中心服务器"))
        self.label.setText(_translate("Dialog", "服务器数量："))
        self.serverNum_comboBox.setItemText(0, _translate("Dialog", "1"))
        self.serverNum_comboBox.setItemText(1, _translate("Dialog", "2"))
        self.serverNum_comboBox.setItemText(2, _translate("Dialog", "3"))
        self.serverNum_comboBox.setItemText(3, _translate("Dialog", "4"))
        self.serverNum_comboBox.setItemText(4, _translate("Dialog", "5"))
        self.label_2.setText(_translate("Dialog", "  主服务器："))
        self.label_3.setText(_translate("Dialog", "端口："))
        self.label_4.setText(_translate("Dialog", "  备服务器："))
        self.label_5.setText(_translate("Dialog", "端口："))
        self.label_6.setText(_translate("Dialog", "   服务器2："))
        self.label_7.setText(_translate("Dialog", "端口："))
        self.label_8.setText(_translate("Dialog", "   服务器3："))
        self.label_9.setText(_translate("Dialog", "端口："))
        self.label_10.setText(_translate("Dialog", "   服务器4："))
        self.label_11.setText(_translate("Dialog", "端口："))
        self.label_12.setText(_translate("Dialog", "   服务器5："))
        self.label_13.setText(_translate("Dialog", "端口："))
        self.groupBox_2.setTitle(_translate("Dialog", "主备中心连接参数设置"))
        self.label_14.setText(_translate("Dialog", "重连间隔（秒）："))
        self.label_15.setText(_translate("Dialog", " 重连次数："))
        self.label_16.setText(_translate("Dialog", "  返回主中心："))
        self.reserver_comboBox.setItemText(0, _translate("Dialog", "否"))
        self.reserver_comboBox.setItemText(1, _translate("Dialog", "是"))
        self.pushButton_2.setText(_translate("Dialog", "配置"))
        self.pushButton_3.setText(_translate("Dialog", "取消"))

