# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'one.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.setEnabled(True)
        Frame.resize(471, 131)
        Frame.setMinimumSize(QtCore.QSize(471, 131))
        Frame.setMaximumSize(QtCore.QSize(471, 131))
        Frame.setStyleSheet("")
        self.groupBox = QtWidgets.QGroupBox(Frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 451, 80))
        self.groupBox.setStyleSheet("color: rgb(170, 0, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.label.setObjectName("label")
        self.netModel_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.netModel_comboBox.setGeometry(QtCore.QRect(70, 10, 81, 21))
        self.netModel_comboBox.setObjectName("netModel_comboBox")
        self.netModel_comboBox.addItem("")
        self.netModel_comboBox.addItem("")
        self.netModel_comboBox.addItem("")
        self.netModel_comboBox.addItem("")
        self.netModel_comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.label_3.setObjectName("label_3")
        self.ID_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ID_lineEdit.setGeometry(QtCore.QRect(70, 50, 81, 20))
        self.ID_lineEdit.setObjectName("ID_lineEdit")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(160, 40, 61, 41))
        self.label_5.setObjectName("label_5")
        self.encryType_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.encryType_comboBox.setGeometry(QtCore.QRect(220, 50, 71, 21))
        self.encryType_comboBox.setObjectName("encryType_comboBox")
        self.encryType_comboBox.addItem("")
        self.encryType_comboBox.addItem("")
        self.encryType_comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(170, 10, 54, 21))
        self.label_2.setObjectName("label_2")
        self.connectMode_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.connectMode_comboBox.setGeometry(QtCore.QRect(230, 10, 61, 22))
        self.connectMode_comboBox.setObjectName("connectMode_comboBox")
        self.connectMode_comboBox.addItem("")
        self.connectMode_comboBox.addItem("")
        self.connectMode_comboBox.addItem("")
        self.connectMode_comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(310, 10, 61, 21))
        self.label_4.setObjectName("label_4")
        self.log_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.log_comboBox.setGeometry(QtCore.QRect(370, 10, 71, 22))
        self.log_comboBox.setObjectName("log_comboBox")
        self.log_comboBox.addItem("")
        self.log_comboBox.addItem("")
        self.log_comboBox.addItem("")
        self.read_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.read_pushButton.setGeometry(QtCore.QRect(350, 50, 41, 21))
        self.read_pushButton.setObjectName("read_pushButton")
        self.ok_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.ok_pushButton.setGeometry(QtCore.QRect(400, 50, 41, 21))
        self.ok_pushButton.setObjectName("ok_pushButton")
        self.reset_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.reset_pushButton.setGeometry(QtCore.QRect(300, 50, 41, 21))
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(Frame)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 451, 43))
        self.groupBox_2.setStyleSheet("color: rgb(170, 0, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.COMset_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.COMset_pushButton.setGeometry(QtCore.QRect(10, 10, 61, 23))
        self.COMset_pushButton.setObjectName("COMset_pushButton")
        self.workModel_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.workModel_pushButton.setGeometry(QtCore.QRect(80, 10, 80, 23))
        self.workModel_pushButton.setObjectName("workModel_pushButton")
        self.IPandPORT_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.IPandPORT_pushButton.setGeometry(QtCore.QRect(170, 10, 80, 23))
        self.IPandPORT_pushButton.setStyleSheet("color: rgb(170, 0, 255);")
        self.IPandPORT_pushButton.setObjectName("IPandPORT_pushButton")
        self.frame_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.frame_pushButton.setGeometry(QtCore.QRect(260, 10, 61, 23))
        self.frame_pushButton.setObjectName("frame_pushButton")
        self.version_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.version_pushButton.setGeometry(QtCore.QRect(330, 10, 61, 23))
        self.version_pushButton.setObjectName("version_pushButton")
        self.reset_pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.reset_pushButton_2.setGeometry(QtCore.QRect(400, 10, 41, 23))
        self.reset_pushButton_2.setObjectName("reset_pushButton_2")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "网络模式："))
        self.netModel_comboBox.setItemText(0, _translate("Frame", "自动"))
        self.netModel_comboBox.setItemText(1, _translate("Frame", "强制3G"))
        self.netModel_comboBox.setItemText(2, _translate("Frame", "强制4G"))
        self.netModel_comboBox.setItemText(3, _translate("Frame", "强制2G"))
        self.netModel_comboBox.setItemText(4, _translate("Frame", "2/3G自适应"))
        self.label_3.setText(_translate("Frame", "DTU设备号："))
        self.label_5.setText(_translate("Frame", "加密类型："))
        self.encryType_comboBox.setItemText(0, _translate("Frame", "不加密"))
        self.encryType_comboBox.setItemText(1, _translate("Frame", "网络加密"))
        self.encryType_comboBox.setItemText(2, _translate("Frame", "串口加密"))
        self.label_2.setText(_translate("Frame", "连接方式："))
        self.connectMode_comboBox.setItemText(0, _translate("Frame", "TCP"))
        self.connectMode_comboBox.setItemText(1, _translate("Frame", "UDP"))
        self.connectMode_comboBox.setItemText(2, _translate("Frame", "DC-TCP"))
        self.connectMode_comboBox.setItemText(3, _translate("Frame", "DC-UDP"))
        self.label_4.setText(_translate("Frame", "调试模式："))
        self.log_comboBox.setItemText(0, _translate("Frame", "否"))
        self.log_comboBox.setItemText(1, _translate("Frame", "是[串口1]"))
        self.log_comboBox.setItemText(2, _translate("Frame", "是[串口2]"))
        self.read_pushButton.setText(_translate("Frame", "读取"))
        self.ok_pushButton.setText(_translate("Frame", "配置"))
        self.reset_pushButton.setText(_translate("Frame", "出厂"))
        self.groupBox_2.setTitle(_translate("Frame", "F2X14(16)-D"))
        self.COMset_pushButton.setText(_translate("Frame", "串口设置"))
        self.workModel_pushButton.setText(_translate("Frame", "工作模式设置"))
        self.IPandPORT_pushButton.setText(_translate("Frame", "企业中心设置"))
        self.frame_pushButton.setText(_translate("Frame", "自定义帧"))
        self.version_pushButton.setText(_translate("Frame", "版本查询"))
        self.reset_pushButton_2.setText(_translate("Frame", "重启"))

