# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'three.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(464, 131)
        Frame.setStyleSheet("")
        self.groupBox = QtWidgets.QGroupBox(Frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 441, 111))
        self.groupBox.setStyleSheet("color: rgb(170, 0, 255);")
        self.groupBox.setObjectName("groupBox")
        self.COMset_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.COMset_pushButton.setGeometry(QtCore.QRect(200, 20, 71, 23))
        self.COMset_pushButton.setObjectName("COMset_pushButton")
        self.IPandPORT_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.IPandPORT_pushButton.setGeometry(QtCore.QRect(110, 20, 81, 23))
        self.IPandPORT_pushButton.setObjectName("IPandPORT_pushButton")
        self.connectSet_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.connectSet_pushButton.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.connectSet_pushButton.setObjectName("connectSet_pushButton")
        self.SMSset_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.SMSset_pushButton.setGeometry(QtCore.QRect(280, 20, 81, 23))
        self.SMSset_pushButton.setObjectName("SMSset_pushButton")
        self.version_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.version_pushButton.setGeometry(QtCore.QRect(160, 77, 61, 23))
        self.version_pushButton.setObjectName("version_pushButton")
        self.state_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.state_pushButton.setGeometry(QtCore.QRect(90, 77, 61, 23))
        self.state_pushButton.setObjectName("state_pushButton")
        self.reset_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.reset_pushButton.setGeometry(QtCore.QRect(230, 77, 61, 23))
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.read_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.read_pushButton.setGeometry(QtCore.QRect(300, 77, 61, 23))
        self.read_pushButton.setObjectName("read_pushButton")
        self.ok_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.ok_pushButton.setGeometry(QtCore.QRect(370, 77, 61, 23))
        self.ok_pushButton.setObjectName("ok_pushButton")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 50, 61, 20))
        self.label.setObjectName("label")
        self.NetModel_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.NetModel_comboBox.setGeometry(QtCore.QRect(70, 50, 86, 20))
        self.NetModel_comboBox.setObjectName("NetModel_comboBox")
        self.NetModel_comboBox.addItem("")
        self.NetModel_comboBox.addItem("")
        self.NetModel_comboBox.addItem("")
        self.NetModel_comboBox.addItem("")
        self.NetModel_comboBox.addItem("")
        self.NetModel_comboBox.addItem("")
        self.NetModel_comboBox.addItem("")
        self.NetModel_comboBox.addItem("")
        self.NetModel_comboBox.addItem("")
        self.NetModel_comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(157, 50, 60, 21))
        self.label_2.setObjectName("label_2")
        self.log_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.log_comboBox.setGeometry(QtCore.QRect(225, 50, 56, 20))
        self.log_comboBox.setObjectName("log_comboBox")
        self.log_comboBox.addItem("")
        self.log_comboBox.addItem("")
        self.log_comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(300, 50, 71, 21))
        self.label_3.setObjectName("label_3")
        self.log_out_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.log_out_comboBox.setGeometry(QtCore.QRect(370, 50, 61, 20))
        self.log_out_comboBox.setObjectName("log_out_comboBox")
        self.log_out_comboBox.addItem("")
        self.log_out_comboBox.addItem("")
        self.log_out_comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(370, 20, 61, 23))
        self.pushButton.setObjectName("pushButton")
        self.worknet_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.worknet_pushButton.setGeometry(QtCore.QRect(10, 77, 71, 23))
        self.worknet_pushButton.setObjectName("worknet_pushButton")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.groupBox.setTitle(_translate("Frame", "F2X16"))
        self.COMset_pushButton.setText(_translate("Frame", "串口设置"))
        self.IPandPORT_pushButton.setText(_translate("Frame", "中心服务"))
        self.connectSet_pushButton.setText(_translate("Frame", "连接协议设置"))
        self.SMSset_pushButton.setText(_translate("Frame", "短信管理"))
        self.version_pushButton.setText(_translate("Frame", "检测版本"))
        self.state_pushButton.setText(_translate("Frame", "状态查询"))
        self.reset_pushButton.setText(_translate("Frame", "恢复出厂"))
        self.read_pushButton.setText(_translate("Frame", "读取"))
        self.ok_pushButton.setText(_translate("Frame", "配置"))
        self.label.setText(_translate("Frame", "网络模式："))
        self.NetModel_comboBox.setItemText(0, _translate("Frame", "AUTO"))
        self.NetModel_comboBox.setItemText(1, _translate("Frame", "仅2G"))
        self.NetModel_comboBox.setItemText(2, _translate("Frame", "仅3G"))
        self.NetModel_comboBox.setItemText(3, _translate("Frame", "仅4G"))
        self.NetModel_comboBox.setItemText(4, _translate("Frame", "EVDO"))
        self.NetModel_comboBox.setItemText(5, _translate("Frame", "WCDMA"))
        self.NetModel_comboBox.setItemText(6, _translate("Frame", "TD-SCDMA"))
        self.NetModel_comboBox.setItemText(7, _translate("Frame", "CDMA"))
        self.NetModel_comboBox.setItemText(8, _translate("Frame", "GSM"))
        self.NetModel_comboBox.setItemText(9, _translate("Frame", "2/3G自适应"))
        self.label_2.setText(_translate("Frame", " 调试等级："))
        self.log_comboBox.setItemText(0, _translate("Frame", "关闭"))
        self.log_comboBox.setItemText(1, _translate("Frame", "等级1"))
        self.log_comboBox.setItemText(2, _translate("Frame", "等级2"))
        self.label_3.setText(_translate("Frame", " 输出接口："))
        self.log_out_comboBox.setItemText(0, _translate("Frame", "串口1"))
        self.log_out_comboBox.setItemText(1, _translate("Frame", "串口2"))
        self.log_out_comboBox.setItemText(2, _translate("Frame", "485"))
        self.pushButton.setText(_translate("Frame", "重启"))
        self.worknet_pushButton.setText(_translate("Frame", "搜网查询"))

