# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WORKmodelDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(252, 268)
        Dialog.setMinimumSize(QtCore.QSize(252, 268))
        Dialog.setMaximumSize(QtCore.QSize(252, 268))
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 231, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.sms_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.sms_comboBox.setObjectName("sms_comboBox")
        self.sms_comboBox.addItem("")
        self.sms_comboBox.addItem("")
        self.gridLayout.addWidget(self.sms_comboBox, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.data_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.data_comboBox.setObjectName("data_comboBox")
        self.data_comboBox.addItem("")
        self.data_comboBox.addItem("")
        self.gridLayout.addWidget(self.data_comboBox, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.active_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.active_lineEdit.setObjectName("active_lineEdit")
        self.gridLayout.addWidget(self.active_lineEdit, 4, 1, 1, 1)
        self.connectType_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.connectType_comboBox.setObjectName("connectType_comboBox")
        self.connectType_comboBox.addItem("")
        self.connectType_comboBox.addItem("")
        self.gridLayout.addWidget(self.connectType_comboBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.phone_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.phone_comboBox.setObjectName("phone_comboBox")
        self.phone_comboBox.addItem("")
        self.phone_comboBox.addItem("")
        self.gridLayout.addWidget(self.phone_comboBox, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.offline_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.offline_lineEdit.setObjectName("offline_lineEdit")
        self.gridLayout.addWidget(self.offline_lineEdit, 5, 1, 1, 1)
        self.cancel_pushButton = QtWidgets.QPushButton(Dialog)
        self.cancel_pushButton.setGeometry(QtCore.QRect(180, 220, 61, 23))
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.read_pushButton = QtWidgets.QPushButton(Dialog)
        self.read_pushButton.setGeometry(QtCore.QRect(40, 220, 61, 23))
        self.read_pushButton.setObjectName("read_pushButton")
        self.ok_pushButton = QtWidgets.QPushButton(Dialog)
        self.ok_pushButton.setGeometry(QtCore.QRect(110, 220, 61, 23))
        self.ok_pushButton.setObjectName("ok_pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "              连接方式："))
        self.sms_comboBox.setItemText(0, _translate("Dialog", "打开"))
        self.sms_comboBox.setItemText(1, _translate("Dialog", "关闭"))
        self.label_3.setText(_translate("Dialog", "              短信激活："))
        self.data_comboBox.setItemText(0, _translate("Dialog", "打开"))
        self.data_comboBox.setItemText(1, _translate("Dialog", "关闭"))
        self.label_5.setText(_translate("Dialog", "定时激活时间间隔（分）："))
        self.connectType_comboBox.setItemText(0, _translate("Dialog", "长连接"))
        self.connectType_comboBox.setItemText(1, _translate("Dialog", "短连接"))
        self.label_2.setText(_translate("Dialog", "              电话激活："))
        self.phone_comboBox.setItemText(0, _translate("Dialog", "打开"))
        self.phone_comboBox.setItemText(1, _translate("Dialog", "关闭"))
        self.label_4.setText(_translate("Dialog", "          本地数据激活："))
        self.label_6.setText(_translate("Dialog", "定时下线时间间隔（分）："))
        self.cancel_pushButton.setText(_translate("Dialog", "取消"))
        self.read_pushButton.setText(_translate("Dialog", "读取"))
        self.ok_pushButton.setText(_translate("Dialog", "配置"))

